#!/bin/bash

# Upgrade pip and install dependencies (no cache to reduce conflicts)
pip install --upgrade pip
pip install --no-cache-dir -r requirements.txt

# Download SpaCy English model
python -m spacy download en_core_web_sm
